### ISSUE TITLE
During install: "npm ERR! code ELIFECYCLE"

### ISSUE THREAD

**Issue by bstr156** [syscoin/Syscoin-Fusion#1]
This is what I've always experienced when trying to install any version of Syscoin Fusion, including the current.  I'm using Ubuntu 18 and following release instructions.
![image](https://user-images.githubusercontent.com/6069215/59116117-6ba57b80-8910-11e9-9290-c1929c337549.png)

**Comment by bstr156** [comment]
Additionally, I did follow the suggested instructions which precede the error output, "Webpack does not work with native dependencies", etc, to no avail.

**Comment by cortesa** [comment]
Follow this procedure in this order(from scratch):

1. Clone the repo:
       `git clone https://github.com/syscoin/Syscoin-Fusion.git`
2. Edit `package.json` and remove
      `"syscoin-js": "git+https://gitlab.com/argvil19/syscoin-js.git#custom_hot_fixes"`
![image](https://user-images.githubusercontent.com/11801422/59123586-d9c45f80-895d-11e9-93c0-6dec5cff6388.png)
3. Run `npm install`
4. Run `npm install git+https://gitlab.com/argvil19/syscoin-js.git#custom_hot_fixes`
5. Copy your OS syscoin dependencies from https://github.com/syscoin/syscoin/releases (or compile yours if you are in linux)  into `extra` folder.
![image](https://user-images.githubusercontent.com/11801422/59124110-1cd30280-895f-11e9-8e3f-e7ebdd83e71d.png)
6. You are done, you can run npm commands now

**Comment by bstr156** [comment]
Thank you for the detailed steps.  I'm not sure if the same issue holds true while installing on other OSes, but this solved the problem for me and I'm using Ubuntu 18.04.

**Comment by Keyare** [comment]
Please retest. Close if pass

**Comment by bstr156** [comment]
Retested.  Passed.
