### ISSUE TITLE
`npm run start`, then error "Something went wrong during wallet initialization. Exiting."

### ISSUE THREAD

**Issue by bstr156** [syscoin/Syscoin-Fusion#2]
When I execute `npm run start`, I see the splash screen, followed by error "Something went wrong during wallet initialization. Exiting."  Here is the terminal buffer at that point during execution.
![buffer](https://user-images.githubusercontent.com/6069215/59131543-4b89b280-8938-11e9-831c-7c98d4318c35.png)

**Comment by bstr156** [comment]
After Cortesa helped me,  I now realize I needed to run the installer produced by `npm run package`, which I had not done.  After installing the .deb package in directory `release` (which is the installer package for Ubuntu), I now see the Fusion icon in my application menu, and it starts fine.

I suggest documentation improvement, specifically more detailed installation steps including launching installation binaries, and which files those are depending on OS.

**Comment by Keyare** [comment]
Plese retest. Close if pass

**Comment by bstr156** [comment]
Retested, passed, closing.
